name: Tests Alice skill

on:
  push:
    branches-ignore: [ main ]
    paths-ignore:
      - '**.md'
      - '**.grammar'
      - '**.txt'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.grammar'
      - '**.txt'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 mypy black isort
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 alice --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 alice --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with mypy
        if: always()
        run: |
          mkdir .mypy_cache
          mypy --config-file mypy.ini --install-types --non-interactive alice
      - name: Lint with black
        if: always()
        run: |
          black --check alice
      - name: Check with isort
        if: always()
        run: |
          isort --check-only alice
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: 'junit.xml'